C:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex> & C:/Users/benjm/AppData/Local/Programs/Python/Python310/python.exe c:/Us
ers/benjm/git/codeHistoriesPythonProjects/Pokedex/pokedex.pyX
X
DevTools listening on ws://127.0.0.1:61649/devtools/browser/358c8e9c-7777-4612-a803-4e23474f34f7X
X> c:\users\benjm\git\codehistoriespythonprojects\pokedex\pokedex.py(60)scrape()
-> row_data = row.find_elements(By.TAG_NAME, "td")X
(Pdb)Xcontinue
X> c:\users\benjm\git\codehistoriespythonprojects\pokedex\pokedex.py(62)scrape()
-> poke_data["name"] = row_data[1].find_element(By.TAG_NAME, "a").textX
(Pdb)Xrow[40424:29856:0623/001055.168:ERROR:device_event_log_impl.cc(214)] [00:10:55.168] USB: usb_device_handle_win.cc:1048 Failed 
to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)X
X_data    [36908:34896:0623/001057.505:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -201
X   row
_data
X*** NameError: name 'rrow_data' is not defined
(Pdb)X[36908:34896:0623/001100.098:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error 
-201X
Xrow_data
X[<selenium.webdriver.remote.webelement.WebElement (session="9055b26bbbe237ff03ae7064968980cc", element="7f73b176-8c65-459b-851d-de81
15cd819b")>, <selenium.webdriver.remote.webelement.WebElement (session="9055b26bbbe237ff03ae7064968980cc", element="820507ba-1617-45
26-aec8-63495ebf207d")>, <selenium.webdriver.remote.webelement.WebElement (session="9055b26bbbe237ff03ae7064968980cc", element="9992
621b-2570-4318-a16f-c41283e4daae")>, <selenium.webdriver.remote.webelement.WebElement (session="9055b26bbbe237ff03ae7064968980cc", e
lement="83bbb66c-bd38-4bb1-9a00-70cd7e516129")>, <selenium.webdriver.remote.webelement.WebElement (session="9055b26bbbe237ff03ae7064
968980cc", element="fbdfff50-0798-4d57-8b8c-509e900a1e3a")>, <selenium.webdriver.remote.webelement.WebElement (session="9055b26bbbe2
37ff03ae7064968980cc", element="dd76d521-2b11-490f-ae9a-d0d9d1661a74")>, <selenium.webdriver.remote.webelement.WebElement (session="
9055b26bbbe237ff03ae7064968980cc", element="1e46cdf9-4cb8-4cab-85ec-c785ec64011e")>, <selenium.webdriver.remote.webelement.WebElemen
t (session="9055b26bbbe237ff03ae7064968980cc", element="7aee61b6-b939-430e-bb00-83f0e0616c91")>, <selenium.webdriver.remote.webeleme
nt.WebElement (session="9055b26bbbe237ff03ae7064968980cc", element="6b704a2a-4f4e-40b5-a6d8-7e9bbf325226")>, <selenium.webdriver.rem
ote.webelement.WebElement (session="9055b26bbbe237ff03ae7064968980cc", element="683642ec-6e7b-400b-ae8e-1d0a70750db4")>]X
(Pdb)Xquit()
XException in Tkinter callback
Traceback (most recent call last):X
  File "C:\Users\benjm\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__X
    return self.func(*args)X
  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 81, in get_pokemonX
    poke_data = scrape(int(poke_id))X
  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 62, in scrapeX
    poke_data["name"] = row_data[1].find_element(By.TAG_NAME, "a").textX
  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 62, in scrapeX
    poke_data["name"] = row_data[1].find_element(By.TAG_NAME, "a").textX
  File "C:\Users\benjm\AppData\Local\Programs\Python\Python310\lib\bdb.py", line 90, in trace_dispatchX
    return self.dispatch_line(frame)X
  File "C:\Users\benjm\AppData\Local\Programs\Python\Python310\lib\bdb.py", line 115, in dispatch_lineX
    if self.quitting: raise BdbQuitX
bdb.BdbQuitX
X[40424:28236:0623/001148.048:ERROR:util.cc(127)] Can't create base directory: C:\Program Files\Google\GoogleUpdater
XTraceback (most recent call last):
  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 148, in <module>X
X    main()
  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 141, in mainX
    run_gui()  # gui is initially empty, prompts user to enter a pokemon IDX
  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 130, in run_guiX
    window.mainloop()  #TODO PROBLEM: this is blockingX
  File "C:\Users\benjm\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1458, in mainloopX
    self.tk.mainloop(n)X
KeyboardInterruptX
Xbdb.BdbQuitX
[40424:28236:0623/001148.048:ERROR:util.cc(127)] Can't create base directory: C:\Program Files\Google\GoogleUpdaterX
Traceback (most recent call last):X
  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 148, in <module>X
    main()X
  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 141, in mainX
    run_gui()  # gui is initially empty, prompts user to enter a pokemon IDX
  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 130, in run_guiX
    window.mainloop()  #TODO PROBLEM: this is blockingX
  File "C:\Users\benjm\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1458, in mainloopX
    self.tk.mainloop(n)X
KeyboardInterruptX
PS 