C:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex> & C:/Users/benjm/AppData/Local/Programs/Python/Python310/python.exe c:/Us
ers/benjm/git/codeHistoriesPythonProjects/Pokedex/pokedex.pyX
X
DevTools listening on ws://127.0.0.1:61977/devtools/browser/63b7251b-6030-44be-8a30-b2ed2470ec57X
X{'name': 'Charmander', 'types': ['FIRE'], 'hp': '39', 'attack': '52', 'defense': '43', 'special attack': '60', 'special defense': '5
0', 'speed': '65'}X
X
DevTools listening on ws://127.0.0.1:62006/devtools/browser/fbb87e18-b203-49ac-a075-f2959908d9d0X
X{'name': 'Venusaur', 'types': ['GRASS', 'POISON'], 'hp': '80', 'attack': '82', 'defense': '83', 'special attack': '100', 'special de
fense': '100', 'speed': '80'}X
X
DevTools listening on ws://127.0.0.1:62050/devtools/browser/645b3244-97f5-493a-be4e-7714c198c4d0X
X{'name': 'Ivysaur', 'types': ['GRASS', 'POISON'], 'hp': '60', 'attack': '62', 'defense': '63', 'special attack': '80', 'special defe
nse': '80', 'speed': '60'}X
X
DevTools listening on ws://127.0.0.1:62088/devtools/browser/2a9f68f2-4b0e-4606-9f01-39c9273aa32fX
XException in Tkinter callback
XTraceback (most recent call last):
  File "C:\Users\benjm\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__X
    return self.func(*args)X
  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 79, in get_pokemonX
    poke_data = scrape(int(poke_id))X
  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 60, in scrapeX
    poke_data["name"] = row_data[1].find_element(By.TAG_NAME, "a").textX
IndexError: list index out of rangeX
X[24616:37956:0623/001251.100:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -101
X[35860:16864:0623/001252.359:ERROR:device_event_log_impl.cc(214)] [00:12:52.359] USB: usb_device_handle_win.cc:1048 Failed to read d
escriptor from node connection: A device attached to the system is not functioning. (0x1F)X
XException in Tkinter callbackX
Traceback (most recent call last):X
  File "C:\Users\benjm\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__X
    return self.func(*args)X
  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 79, in get_pokemonX
    poke_data = scrape(int(poke_id))X
  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 60, in scrapeX
    poke_data["name"] = row_data[1].find_element(By.TAG_NAME, "a").textX
IndexError: list index out of rangeX
[24616:37956:0623/001251.100:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -101  
[35860:16864:0623/001252.359:ERROR:device_event_log_impl.cc(214)] [00:12:52.359] USB: usb_device_handle_win.cc:1048 Failed to read d
escriptor from node connection: A device attached to the system is not functioning. (0x1F)X
XPS 