C:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex> & C:/Users/benjm/AppData/Local/Programs/Python/Python310/python.exe c:/Us
ers/benjm/git/codeHistoriesPythonProjects/Pokedex/pokedex.pyX
X
DevTools listening on ws://127.0.0.1:56736/devtools/browser/b839bad9-79f0-4144-9006-59142a55749eX
XException in Tkinter callback
XTraceback (most recent call last):
  File "C:\Users\benjm\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__X
    return self.func(*args)X
  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 81, in get_pokemonX
    poke_data = scrape(int(poke_id))X
  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 62, in scrapeX
    poke_data["name"] = row_data[1].find_element(By.TAG_NAME, "a").textX
IndexError: list index out of rangeX
X[26100:37752:0623/000735.368:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -101
X[26100:37752:0623/000735.885:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -201
X[41476:38144:0623/000737.143:ERROR:device_event_log_impl.cc(214)] [00:07:37.142] USB: usb_device_handle_win.cc:1048 Failed to read d
escriptor from node connection: A device attached to the system is not functioning. (0x1F)X
XTraceback (most recent call last):
X  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 148, in <module>
    main()X
  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 141, in mainX
    run_gui()  # gui is initially empty, prompts user to enter a pokemon IDX
  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 130, in run_guiX
    window.mainloop()  #TODO PROBLEM: this is blockingX
  File "C:\Users\benjm\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1458, in mainloopX
    self.tk.mainloop(n)X
KeyboardInterruptX
X[41476:38144:0623/000737.143:ERROR:device_event_log_impl.cc(214)] [00:07:37.142] USB: usb_device_handle_win.cc:1048 Failed to read d
escriptor from node connection: A device attached to the system is not functioning. (0x1F)X
Traceback (most recent call last):X
  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 148, in <module>X
    main()X
  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 141, in mainX
    run_gui()  # gui is initially empty, prompts user to enter a pokemon IDX
  File "c:\Users\benjm\git\codeHistoriesPythonProjects\Pokedex\pokedex.py", line 130, in run_guiX
    window.mainloop()  #TODO PROBLEM: this is blockingX
  File "C:\Users\benjm\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1458, in mainloopX
    self.tk.mainloop(n)X
KeyboardInterruptX
XPS 